
info:
    description:
        "LiferayRkRestbuilder REST API. A Java client JAR is available for use with the group ID 'com.liferay', artifact
        ID 'com.liferay.rk.rest.builder.client', and version '1.0.0'."
    license:
        name: "Apache 2.0"
        url: "http://www.apache.org/licenses/LICENSE-2.0.html"
    title: "LiferayRkRestbuilder"
    version: v1.0
openapi: 3.0.1

paths:
  "/get-user":
    get:
      operationId: getUserById
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: "Success Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserObject"
            application/xml:
              schema:
                $ref: "#/components/schemas/UserObject"
      tags: ["User"]
  "/get-users":
    get:
      operationId: getUsers
      parameters:
        - in: query
          name: page
          schema:
            type: integer
        - in: query
          name: pageSize
          schema:
            type: integer
      responses:
        200:
          description: "Success Response"
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/UserObject"
            application/xml:
              schema:
                items:
                  $ref: "#/components/schemas/UserObject"
      tags: ["User"]
  "/update-user":
    post:
      operationId: updateUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserObject"
          application/xml:
            schema:
              $ref: "#/components/schemas/UserObject"
      responses:
        200:
          description: "Success Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserObject"
            application/xml:
              schema:
                $ref: "#/components/schemas/UserObject"
      tags: ["User"]
  "/delete-user":
    delete:
      operationId: deleteUserById
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: "Success Response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserObject"
            application/xml:
              schema:
                $ref: "#/components/schemas/UserObject"
      tags: ["User"]
components:
  schemas:
    UserObject:
      properties:
        userId:
          type: integer
          format: int64
        screenName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        statusCode:
          type: integer
        statusMessage:
          type: string